name: Publish CI

on:
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm ci

      - name: Pre-build
        run: script/addEditLinks.py

      - name: Build 🔧
        run: PUBLIC_URL=/techradar-android npx aoe_technology_radar-buildRadar

      - name: Build Static site 🔧
        run: PUBLIC_URL=/techradar-android npx aoe_technology_radar-createStaticFiles
      
      - name: Generate Data 🔧
        run: npx aoe_technology_radar-generateJson

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true